FROM python:3.10-slim
WORKDIR /mlflow
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
CMD ["mlflow", "ui", "--backend-store-uri", "file:/mlruns", "--host", "0.0.0.0"]
